### ISSUE TITLE
capital letters in properties

### ISSUE THREAD

**Issue by giorgialodi** [isa-camss/CAV#16]
it should be dct:description with no capital letter, The same applies to xsd:string

**Comment by jseguraf** [comment]
This is to be solved globaly since the CAV has to be aligned to the SEMIC style guide, which is an on-going work. Since this work is not yet stable and has not been published, the governance decission is to align the CAV to the [ePO](https://github.com/eprocurementontology/eprocurementontology/wiki) conventions rules. The rationale for this decision is to use the artefacts that convert the UML into the RDF-based serialisation.
